name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - review_requested
      - closed
      - converted_to_draft
jobs:
  ProjectAutomations:
    runs-on: ubuntu-latest
    steps:
      - name: 'Move issue to "ğŸ“– To do"'
        if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          organization: Oztechan
          project_id: 2
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "ğŸ“– To do"

      - name: 'Moved issue to "âœ… Done"'
        if: github.event_name == 'issues' && github.event.action == 'closed'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          organization: Oztechan
          project_id: 2
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "âœ… Done"

      - name: 'Move PR to "ğŸš§ In Progress"'
        if: github.event_name == 'pull_request' && github.event.action == 'converted_to_draft'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          organization: Oztechan
          project_id: 2
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: "ğŸš§ In Progress"

      - name: 'Move PR to "ğŸ— PR Review"'
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review')
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          organization: Oztechan
          project_id: 2
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: "ğŸ— PR Review"

      - name: 'Move PR to "âœ… Done"'
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          organization: Oztechan
          project_id: 2
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: "âœ… Done"
